import { Link } from 'react-router-dom';

import { RiskBadge } from '../components/ui/RiskBadge.jsx';
import { EmptyState, ErrorState, SkeletonTable } from '../components/ui/States.jsx';
import { Topbar } from '../components/layout/Topbar.jsx';
import { PageTransition } from '../components/ui/motion.jsx';
import { api } from '../lib/api.js';
import { fmtRelative } from '../lib/format.js';
import { useAsync } from '../lib/useAsync.js';

/** Generated investigation reports, newest first. Each links to the print-ready view. */
export function Reports() {
  const { data, loading, error, reload } = useAsync(() => api.listReports(), []);

  return (
    <>
      <Topbar title="Reports" subtitle="Generated investigation briefs" />
      <main className="flex-1 overflow-y-auto p-6">
        <PageTransition className="mx-auto max-w-4xl">
          <div className="overflow-hidden rounded-xl border border-line bg-surface">
            {loading ? (
              <SkeletonTable rows={6} />
            ) : error ? (
              <ErrorState error={error} onRetry={reload} />
            ) : data.results.length === 0 ? (
              <EmptyState
                title="No reports yet"
                description="Open a high-risk transaction and generate an investigation report to see it here."
              />
            ) : (
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-line text-left text-xs font-medium text-muted">
                    <th className="px-4 py-2.5">Risk</th>
                    <th className="px-4 py-2.5">Transaction</th>
                    <th className="px-4 py-2.5">Generated by</th>
                    <th className="px-4 py-2.5">Generated</th>
                    <th className="px-4 py-2.5" />
                  </tr>
                </thead>
                <tbody>
                  {data.results.map((r) => (
                    <tr key={r._id} className="border-b border-line/60 last:border-0 hover:bg-elevated">
                      <td className="px-4 py-3"><RiskBadge band={r.snapshot.riskBand} score={r.snapshot.compositeScore} /></td>
                      <td className="px-4 py-3 font-mono text-xs text-muted">{r.transactionId.slice(0, 16)}</td>
                      <td className="px-4 py-3 text-fg">{r.generatedByName}</td>
                      <td className="px-4 py-3 text-muted">{fmtRelative(r.createdAt)}</td>
                      <td className="px-4 py-3 text-right">
                        <Link to={`/reports/${r._id}/view`} className="text-sm font-medium text-accent-400 hover:text-accent-300">
                          View →
                        </Link>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </PageTransition>
      </main>
    </>
  );
}
